### ISSUE TITLE
No days?

### ISSUE THREAD

**Issue by VyIq** [Mac0r0ni/kikKREATOR#1]
Does this make no day accounts? And if so do you know why, possibly the device id and android id?

**Comment by Mac0r0ni** [comment]
> Does this make no day accounts? And if so do you know why, possibly the device id and android id?

i poop twice daily

**Comment by VyIq** [comment]
😡

**Comment by Mac0r0ni** [comment]
> rage

That's my face when I go poopin'

**Comment by VyIq** [comment]
Eat more fiber

**Comment by DuzziOmacron** [comment]
Baaaahahaahahh you gotta be able to withstand the macaronii should you want a taste!
