### ISSUE TITLE
When i run the script nothing happens

### ISSUE THREAD

**Issue by MisterEight** [Mac0r0ni/kikKREATOR#6]
I think my problem is at line 59, if is something like wrong dependencies or some details, let me know

**Comment by Mac0r0ni** [comment]
Hello. What error messages you received? (if any)

The most common issue is not replace the file path of your chromedriver in line [104 of register.py](https://github.com/Mac0r0ni/kikKREATOR/blob/279da23b2f7ee354ea2ed4c789c43fa0de7fadeb/register.py#L104)

Second most common issue is not having the directories right. you can check out [this comment](https://github.com/tomer8007/kik-bot-api-unofficial/issues/217#issuecomment-1249965574)

**Comment by MisterEight** [comment]
Thanks for the fast response, the problem is that I am getting no error message.
The script just run indefinitely after it gets to line 59.
About ChromeDriver, i don't know if is correct but heres the path:
Sorry If i am making a newbie mistake, it's my first time working with chromedriver
![image](https://user-images.githubusercontent.com/103611605/213031746-9dcd073f-40b7-4e32-ae1a-10e0f49eb5cb.png)

**Comment by MisterEight** [comment]
![image](https://user-images.githubusercontent.com/103611605/213032133-477fd5c9-ca76-486a-8d32-720bb924ec5c.png)

**Comment by MisterEight** [comment]
![image](https://user-images.githubusercontent.com/103611605/213032270-36b637e4-ac8f-4fdf-92ff-1c238025ae0f.png)

**Comment by Mac0r0ni** [comment]
kik_unofficial > client.py line # 79

could you report back what that line is?

**Comment by MisterEight** [comment]
![image](https://user-images.githubusercontent.com/103611605/213039071-11d84ab4-c534-4010-a40d-4a4c92ce1258.png)
Line 79, sorry for the slow response

**Comment by MisterEight** [comment]
![image](https://user-images.githubusercontent.com/103611605/213039449-a3c175c8-d7d0-4795-9d50-94d295db3245.png)

**Comment by MisterEight** [comment]
After leaving the script running for a while the console showed this
![image](https://user-images.githubusercontent.com/103611605/213045235-1e2cc4f4-f804-4864-a5d1-0b144b95fad1.png)

**Comment by Mac0r0ni** [comment]
delete line #79 in client.py and try agian

**Comment by MisterEight** [comment]
![image](https://user-images.githubusercontent.com/103611605/213048528-22cb5cc4-63a8-41f6-8063-fd283a8112b8.png)
After i remove 79 line the code is like that
and i get this error
![image](https://user-images.githubusercontent.com/103611605/213049002-1ec4dc57-4a86-424a-acb6-c6e13da8989e.png)

**Comment by Mac0r0ni** [comment]
delete self.kik_connection_thread.join()

**Comment by MisterEight** [comment]
![image](https://user-images.githubusercontent.com/103611605/213053085-bccf2edb-f19a-453f-b379-40277caf363b.png)
The code
The error
![image](https://user-images.githubusercontent.com/103611605/213053111-017942b5-0010-4423-b5bd-b6977305f8e4.png)

**Comment by Mac0r0ni** [comment]
` def _connect(self):
        """
        Runs the kik connection thread, which creates an encrypted (SSL based) TCP connection
        to the kik servers.
        """
        self.kik_connection_thread = Thread(target=self._kik_connection_thread_function, name="Kik Connection")
        self.kik_connection_thread.start()`

**Comment by Mac0r0ni** [comment]
def _connect(self):
        """
        Runs the kik connection thread, which creates an encrypted (SSL based) TCP connection
        to the kik servers.
        """
        self.kik_connection_thread = Thread(target=self._kik_connection_thread_function, name="Kik Connection")
        self.kik_connection_thread.start()

**Comment by MisterEight** [comment]
Still nothings happens
![image](https://user-images.githubusercontent.com/103611605/213182889-65f84baa-b6fb-42d0-9790-2fd433f803fb.png)
![image](https://user-images.githubusercontent.com/103611605/213182956-2fae1eb2-1c7e-4d5d-b837-0c56c040d1ce.png)
![image](https://user-images.githubusercontent.com/103611605/213182992-e3700007-4df6-4163-a318-8b54f0ce4647.png)

**Comment by Mac0r0ni** [comment]
Oh I just see you using python 11,  check out this following.

https://github.com/tomer8007/kik-bot-api-unofficial/issues/172

**Comment by MisterEight** [comment]
I will test that, come back later

**Comment by Mac0r0ni** [comment]
Reopen if more assistance is needed
